### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: The dataset should not be empty

### ISSUE THREAD

**Issue by AlexWanghaoming** [LiuLabUB/HMMRATAC#15]
Dear LiuLab,
When I ran HMMRATAC, I met this error:

> Exception in thread "main" java.lang.RuntimeException: The dataset should not be empty
> 	at net.sf.javaml.clustering.KMeans.cluster(KMeans.java:120)
> 	at RobustHMM.KMeansToHMM.build(KMeansToHMM.java:86)
> 	at RobustHMM.KMeansToHMM.<init>(KMeansToHMM.java:31)
> 	at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:344)

What's the problem might be?
Thanks

**Comment by EvanTarbell** [comment]
This error indicates that the training matrix is empty. It might be the case where the -u and -l options are too stringent and no sites meet that criteria, hence the empty matrix. You can try lowering the range (ie lower both -u and -l together) or expanding the range (ie increasing -u and lowering -l) to capture more training sites. The error can also be caused by user error sometimes. For instance, if the chr names dont match between the BAM file and genome file (for instance chr1 in BAM and 1 in genome file)

**Comment by AlexWanghaoming** [comment]
Thank you EvanTarbell. 
We use -u 15 -l 5  / -u 18 -l 8 to call peaks in fungi genome with deep sequencing ATAC-Seq data. Comparing with 7715 peaks with MACS2, I only get 351/187 peaks using HMMRATAC, I do not know how to explain this disparity.
Thank you again, EvanTarbell

**Comment by EvanTarbell** [comment]
The first thing you should check is the model that is created. It can be found in the log file. There should be two models that are described in the log file, one is the initial model made via KMeans clustering and the second is the model built by the Baum Welch algorithm.  The Kmeans model will show proportional transitions between states (ie .333 for a 3 state model) while the BW model shouldn't.  A proper model should show the highest emission values in the final state, for all 4 emission values.  Assuming that the model is good, then this might simply be a threshold issue. You can try lowering the -l option even further, say to 2 (-l 2) and see how that works.

**Comment by AlexWanghaoming** [comment]
Thanks, EvanTarbell.
We get more peaks when extending training dataset.
