### ISSUE TITLE
FR: Please include some sample data that will produce a known result

### ISSUE THREAD

**Issue by GodloveD** [LiuLabUB/HMMRATAC#37]
Hi there!  I've been trying to validate this tool before installing, and I'm running into some trouble finding the correct kind of data to give it.  

## problem
I'm an admin trying to test this software on behalf of a user.  I have some `.bam` files that other admins use as test data, but when I follow the quickstart steps, I get errors telling me that the `.bam` file header is incorrect or that the data needs to be paired read.  I realize that these are probably trivial errors that someone with an omics background could solve easily, but it would be nice to be able to install and test this software on behalf of someone else.

## solution
Including some test data with the source code along with (real) example commands and expected results would greatly help people like me who install and validate software on behalf of other users.  

## additional benefits
Having some test data that produces a known result seems like it would be a prerequisite for #36, and might produce a nice starting point.  

Thanks for considering this feature request!  

😄

**Comment by taoliu** [comment]
I think Evan is working on it, using his precious spare time :)

**Comment by EvanTarbell** [comment]
I have uploaded a series of files for testing. The data is only from chr22 and comes from the monocyte data that was analyzed in our paper. The data corresponds to the treatment "RPMI for 4 hours" from "Novakovic B, et al. β-Glucan Reverses the Epigenetic State of LPS-Induced Immunological Tolerance. Cell 2016 PMID: 27863248".  Included are the files needed to run HMMRATAC (BAM, BAI, genome file), as well as the expected output from version 1.2.9 with default settings (check the log file to see all settings when the data was run).  One thing to keep in mind, is that due to the random selection of training regions, there _may_ be slight differences between runs. The numbers of called peaks should be similar and the overlap between runs should be very high, although not likely exact.

**Comment by JihedC** [comment]
Hi @GodloveD ,

Did you find a solution for the wrong `.bam` files. I think I have the same problem with mine?

thanks!

**Comment by GodloveD** [comment]
Hey @JihedC.  Sorry, I really never needed to run the sample `.bam` files that I tried in the first comment.  The example data worked for me, so I just used that for validation and moved on.  Maybe those files have some hints in them that could help you figure out why your `.bam` files don't work?

**Comment by JihedC** [comment]
Hi @GodloveD 

Thanks for your quick reply. Yes that's a good idea.
For now I always get `Exception in thread "main" java.lang.IllegalStateException: Inappropriate call if not paired read`
For every bam file I generated with bowtie2.
