### ISSUE TITLE
Q: What should we do to output the HMMRATAC results in a format so that differential peak analysis can be conducted? What tool for differential peak analysis do you recommend?

### ISSUE THREAD

**Issue by liangcmu** [LiuLabUB/HMMRATAC#53]
**Use case**
A clear and concise description of what the use case is. For example: my data is from [...]

**Describe the problem**
A clear and concise description of what happend.

**Describe the solution you tried**
A clear and concise description of any solutions you've tried.

**Additional context**
Add any other context or screenshots about your use case here.

**Comment by EvanTarbell** [comment]
See issue #40 
I recommend using DiffBind and the summits outputted by HMMRATAC. HOWEVER, i dont generally believe that any differential analysis tool is optimal for ATAC-seq, because none of them account for the structure, which HMMRATAC has shown is critical. I am developing a differential tool based on the HMMRATAC framework that will account for these issues, does seem to do better than current count based tools, but it is not yet published or peer reviewed. So in the meantime, DiffBind and the summits is probably your best bet
