### ISSUE TITLE
Q: Interpreting E1/E2 states when doing differential accessibility analysis 

### ISSUE THREAD

**Issue by nyuhic** [LiuLabUB/HMMRATAC#67]
Hello,

I am trying to do differential analysis between two conditions and and was a bit confused about how to interpret the results. You have mentioned in the some other threads, tools like diffbind are not ideal for ATAC-seq but can be used if needed. I have used a deseq2 based pipeline similar to diffbind to do the differential analysis. I ran  HMMRATAC with default settings, extended the resulting summit files to 500bp, merged them between conditions and then did the differential analysis to identify regions becoming more or less open. I then plotted the signal from the bedgraph files produced by HMMRATAC (total signal or split into E1 and E2)) across these differentially accessible regions. Here are the plots for some regions that are becoming more accessible in my treatment condition. 

![Untitled](https://user-images.githubusercontent.com/49555006/87524109-d2ab6d00-c698-11ea-88d8-1e3c14201149.png)

The change in total signal is pretty obvious but I am not sure how to interpret the E1 and E2 plots. It seems most of the change in signal is coming from the nucleosomal state while the NFR state remains relatively unchanged. I am not sure what this means in terms of the biology and if it says something about nucleosome occupancy or not. Do you have any comments on these plots and if this type of analysis makes sense?

Thanks

**Comment by EvanTarbell** [comment]
I dont think what is being plotted is the best way to show what i think youre trying to show. The score outputted by HMMRATAC is used as a threshold for deciding whether the genomic annotation is true. Its problematic to use the peak (or annotation) score in these plots, because of the variability in peak size. Imagine two peaks, both with a score of 10, with one peak being 200bp long and the other being 300bp long. Using your approach, all 200 bp of the first peak are set to a value of 10 and all 300bp of the second peak are set to a value of 10. Moreover, the score (at least with default options) represents the maximum score across the peak. So even though all bps in the peak are set to the same value in your approach, that isnt the case in reality. The better approach would be to plot the raw (or normalized - by some procedure) ATAC-seq signal across your differentially accessible regions. Ultimately this should show what you would expect (something similar to your "total" plot above). 
Now if you wanted to know if the differentially accessible regions (DAR) were the result of differential nucleosome occupancy, or differences in signal intensity, you could try seeing if your DARs are more or less enriched for nucleosome positions compared to non-DARs. I don't know whether that would tell you or not, however, because most software will probably be biased towards changes in signal as opposed to changes in annotation (the whole point behind why i say that current software is inadequate with ATAC-seq).
