### ISSUE TITLE
Q: how evaluate the model?

### ISSUE THREAD

**Issue by trn30** [LiuLabUB/HMMRATAC#68]
When i execute the program with:
`java -jar HMMRATAC.jar -b ATAC.sorted.bam -i ATAC.sorted.bam.bai -g genome.info -o out_HMM -q 10 --bedgragh true  --minlen 100`
My results are very poor, i only have 230 peaks without the filtering, while if I use MACS2, I obtain 6448 peaks. Using bedtools intersect i try to see how many of these peaks are the same and even if the number isn't similar the peaks of HMMRATC correspond to the highest intensity peaks that result in MACS2. Doing this, only 149 peaks are the same in both and they aren't the most intense of the 6448 resulting from MACS2.

Reading the manual and the method that the program uses to get the results, i saw that if the model its poor probably the algorithm get wrong results. Because of that I check the .log and the numbers referred to the model seem strange to me.

 This is a fragment of the .log :

> Fragment Expectation Maximum Done
> Mean	50.0	StdDevs	20.0
>    Mean	182.83389929726104	StdDevs	56.12618765652857
>    Mean	396.48266594891635	StdDevs	51.03194458292357
>    Mean	637.7072007289707	StdDevs	103.85759952563862
>    ScalingFactor	1.205004
>    Training Regions found and Zscore regions for exclusion found
>    Training Fragment Pileup completed
>    Kmeans Model:
>    HMM with 3 state(s)
> 
>    State 0
>      Pi: 0.3333333333333333
>      Aij: 0.333 0.333 0.333
>      Opdf: Multi-variate Gaussian distribution --- Mean: [ 0.003 0.002 0.001 0.013 ]
> 
>    State 1
>      Pi: 0.3333333333333333
>      Aij: 0.333 0.333 0.333
>      Opdf: Multi-variate Gaussian distribution --- Mean: [ 0.215 0.357 0.864 0.288 ]
> 
>    State 2
>      Pi: 0.3333333333333333
>      Aij: 0.333 0.333 0.333
>      Opdf: Multi-variate Gaussian distribution --- Mean: [ 0.646 0.72 0.105 0.052 ]
> 
>    Model created and refined. See NA.model
>    Model:
>    HMM with 3 state(s)
> 
>    State 0
>       Pi: 0.3333333333333333
>       Aij: 0.985 0.003 0.013
>      Opdf: Multi-variate Gaussian distribution --- Mean: [ 0 0 0 0 ]
> 
>    State 1
>      Pi: 0.3333333333333333
>      Aij: 0.015 0.976 0.008
>      Opdf: Multi-variate Gaussian distribution --- Mean: [ 0.322 0.561 0.586 0.289 ]
> 
>    State 2
>      Pi: 0.3333333333333333
>      Aij: 0.09 0.01 0.9
>      Opdf: Multi-variate Gaussian distribution --- Mean: [ 0.669 0.566 0.006 0.003 ]
> 
>    Genome split and subtracted masked regions
>    0 round viterbi done
>    50 round viterbi done
>    92 round viterbi done

How can I know if the model is correct or if y have to change some parameters? 
I would appreciate the help.
Thanks!

**Comment by EvanTarbell** [comment]
From the user guide:

> Tips for checking model.

The creation of a proper model is critial for HMMRATAC. It is always recommended to check the log file and visually examine the model to confirm that a proper one has been created. The open state should have the highest emission parameters for all 4 signal components, the nucleosome state should have the second highest emission parameters for all 4 signal components and the background state should have the lowest emission parameters for all 4 signal components. If this is not the case, the model is likely bad. **An example is a case where the open state has the highest NFR and mononucleosome emission values, but the second highest dinucleosome and trinucleosome emission values.** This often happens when there isn't enough separation in the values between states (similar to item 3 above). A typcial fix would be to re-run the software with a more stringent set of parameters (-u and -l, similar to item 3 above). Another possible issue is that the log file shows that the kmeans model is identical to the final model. In the event that Baum Welch training fails, HMMRATAC will use the original Kmeans model in order to produce some result. Because the kmeans model doesn't include transition parameters, this is also not ideal. The way to solve this issue, is the same as above, namely setting mote stringent parameters to create more separation in the values between states.

Your model appears to suffer from this problem. Increasing the -u and -l parameters are the way to fix this issue.

**Comment by hhvu0102** [comment]
Hi Evan,
I want to clarify something. say this is a piece of information I got in my log file:

> State 0
  Pi: 0.3333333333333333
  Aij: 0.333 0.333 0.333
  Opdf: Multi-variate Gaussian distribution --- Mean: [ 0.064 0.096 0.066 0.044 ]

1. What is State 0 here? Is it the center, or the background region?
2. What do the numbers `Mean: [ 0.064 0.096 0.066 0.044 ]` here correspond to? Is `0.064`, the first number, the emission parameter for the first signal component?

I also have a suggestion: Is it possible that you create a documentation to explain an example log file? It would help a lot.

Thanks!

**Comment by EvanTarbell** [comment]
To answer your questions:
1) It is the background state. State 2 (assuming -k 3 which is the default setting) would be the center state
2) Yes, that is the first signal component, the NFR (nucleosome-free) signal. The second value is the 1N (mono-nucleosome) signal, followed by the 2N (di-nucleosome) and 3N (tri-nucleosome) signal.

As for your suggestion, that is a great idea! I will work on that. 

Lastly, you can see with the transition parameters (Aij) that they states have equal transition probability. This means that the training step didnt work. You'll see that this model is identical to the "initial" one. This indicates that Baum Welch training failed. You will likely need to increase the -u and -l parameters.
