### ISSUE TITLE
threshold for reporting peaks

### ISSUE THREAD

**Issue by igordot** [LiuLabUB/HMMRATAC#74]
In the README and the [guide](https://github.com/LiuLabUB/HMMRATAC/blob/master/HMMRATAC_Guide.md), the suggested threshold value for filtering is 10. However, in the [code](https://github.com/LiuLabUB/HMMRATAC/blob/ca552fb6822a53fe323ae3fe54a607ee47bda08c/src/main/java/HMMR_ATAC/ArgParser.java#L61), the default cutoff is 30 (it's not specified in the usage). Thus, the filtering would not do anything. Do you have any suggestion for which cutoff value is more reasonable?

**Comment by EvanTarbell** [comment]
This is a good question and I dont have the best answer. Like with all peak callers, it depends on what the user wants. Higher specificity would mean a higher threshold, while higher sensitivity would require a lower threshold. I chose 30 because this gave a result similar (in terms of sensitivity) as the default thresholds in MACS2 and FSEQ.
