### ISSUE TITLE
Can almost failed ATAC-seq library used for peak calling in HMMRATAC 

### ISSUE THREAD

**Issue by RadPa** [LiuLabUB/HMMRATAC#82]
The data entails two samples with replicates.

I am not sure if I can use HMMRATAC and the right parameters for peak calling if used.

I am planning to use --trim 2, but not sure if that's correct.

![FLD](https://user-images.githubusercontent.com/49912152/110580341-74368000-818e-11eb-9dee-7d1e6510ce59.png)

**Comment by EvanTarbell** [comment]
I think you can give it a try. I wouldn't use --trim, you seem to have reads that are 400bp (di-nucleosomes) and reads ~600bp (tri-nucleosomes). i think your samples should work, certainly the AAT2 and ANT2 samples. I can't tell with this color scheme, but the AAT1/ANT1 with the small peak around 50bp should be ok too. It seems like there is a bias towards mono-nucleosome-sized reads as opposed to short ones (compared to what your seeing with AAT2/ANT2) but the small sized peak (around 50bp) is there so that should be ok too. The ANT2/AAT2 sample without that 50bp peak might be the one to cause problems. I still think it could work, though. You can paste the log files that are created when running HMMRATAC here and I can check for problems after you give it a try

**Comment by RadPa** [comment]
Thank you for the reply.
I will paste the log files once I have created them.
Thank you.

**Comment by RadPa** [comment]
I am pasting the log files and created with the default parameter except for the mapq values. 
Thank you for your time.

[ANT1.log](https://github.com/LiuLabUB/HMMRATAC/files/6120785/ANT1.log)
[ANT2.log](https://github.com/LiuLabUB/HMMRATAC/files/6120786/ANT2.log)
[AAT1.log](https://github.com/LiuLabUB/HMMRATAC/files/6120789/AAT1.log)
[AAT2.log](https://github.com/LiuLabUB/HMMRATAC/files/6120790/AAT2.log)

**Comment by EvanTarbell** [comment]
The log files look good and the models that were generated also look good.

**Comment by RadPa** [comment]
Thank you for your comments about the library, I was worried and had my doubts, now I can proceed with a bit more confidence. 
Thanks again.
